#define ascii_NUL 0
#define ascii_SOH 1
#define ascii_STX 2
#define ascii_ETX 3
#define ascii_EOT 4
#define ascii_ENQ 5
#define ascii_ACK 6
#define ascii_BEL 7
#define ascii_BS 8
#define ascii_HT 9
#define ascii_LF 10
#define ascii_VT 11
#define ascii_FF 12
#define ascii_CR 13
#define ascii_SO 14
#define ascii_SI 15
#define ascii_DLE 16
#define ascii_DC1 17
#define ascii_DC2 18
#define ascii_DC3 19
#define ascii_DC4 20
#define ascii_NAK 21
#define ascii_SYN 22
#define ascii_ETB 23
#define ascii_CAN 24
#define ascii_EM 25
#define ascii_SUB 26
#define ascii_ESC 27
#define ascii_FS 28
#define ascii_GS 29
#define ascii_RS 30
#define ascii_US 31
#define ascii_SPACE 32
#define ascii_EXCLAMATION 33 /* ! */
#define ascii_DOUBLEQUOTE 34 /* " */
#define ascii_HASH 35 /* # */
#define ascii_DOLLAR 36 /* $ */
#define ascii_PERCENT 37 /* % */
#define ascii_AMPERSAND 38 /* & */
#define ascii_SINGLEQUOTE 39 /* ' */
#define ascii_LEFTCURLYBRACE 40 /* ( */
#define ascii_RIGHTCURLYBRACE 41 /* ) */
#define ascii_ASTERISK 42 /* * */
#define ascii_PLUS 43 /* + */
#define ascii_COMMA 44 /* , */
#define ascii_MINUS 45 /* - */
#define ascii_PERIOD 46 /* . */
#define ascii_FORWARD_SLASH 47 /* / */
#define ascii_0 48
#define ascii_1 49
#define ascii_2 50
#define ascii_3 51
#define ascii_4 52
#define ascii_5 53
#define ascii_6 54
#define ascii_7 55
#define ascii_8 56
#define ascii_9 57
#define ascii_COLON 58 /* : */
#define ascii_SEMICOLON 59 /* ; */
#define ascii_LEFTANGLEBRACKET 60 /* < */
#define ascii_EQUAL 61 /* = */
#define ascii_RIGHTANGLEBRACKET 62 /* > */
#define ascii_QUESTIONMARK 63 /* ? */
#define ascii_ATSIGN 64 /* @ */
#define ascii_A 65
#define ascii_B 66
#define ascii_C 67
#define ascii_D 68
#define ascii_E 69
#define ascii_F 70
#define ascii_G 71
#define ascii_H 72
#define ascii_I 73
#define ascii_J 74
#define ascii_K 75
#define ascii_L 76
#define ascii_M 77
#define ascii_N 78
#define ascii_O 79
#define ascii_P 80
#define ascii_Q 81
#define ascii_R 82
#define ascii_S 83
#define ascii_T 84
#define ascii_U 85
#define ascii_V 86
#define ascii_W 87
#define ascii_X 88
#define ascii_Y 89
#define ascii_Z 90
#define ascii_LEFTSQRBRACKET 91 /* [ */
#define ascii_BACKSLASH 92 /* \ */
#define ascii_RIGHTSQRBRACKET 93 /* ] */
#define ascii_CARET 94 /* ^ */
#define ascii_UNDERSCORE 95 /* _ */
#define ascii_GRAVEACCENT 96 /* ` */
#define ascii_a 97
#define ascii_b 98
#define ascii_c 99
#define ascii_d 100
#define ascii_e 101
#define ascii_f 102
#define ascii_g 103
#define ascii_h 104
#define ascii_i 105
#define ascii_j 106
#define ascii_k 107
#define ascii_l 108
#define ascii_m 109
#define ascii_n 110
#define ascii_o 111
#define ascii_p 112
#define ascii_q 113
#define ascii_r 114
#define ascii_s 115
#define ascii_t 116
#define ascii_u 117
#define ascii_v 118
#define ascii_w 119
#define ascii_x 120
#define ascii_y 121
#define ascii_z 122
#define ascii_LEFTSQUIGGLYBRACE 123 /* { */
#define ascii_PIPE 124
#define ascii_RIGHTSQUIGGLYBRACE 125 /* } */
#define ascii_TILDE 126 /* ~ */
#define ascii_DEL 127
